name: rxmc
channels:
  - conda-forge
dependencies:
  - git=2.34.1
  - ipython
  - jupyter
  - matplotlib
  - mpi4py
  - openssh
  - openssl
  - pip
  - pipreqs
  - python
  - setuptools
  - pip:
    - build==1.2.2.post1
    - pipreq==0.4
